### PR TITLE
Update campaigns.types.ts

### PR DESCRIPTION
**Pull request by olawalejuwonm**
Fix Incorrect Typings #42

### CODE REVIEW

**Review by Mantas97 — APPROVED** [review]
Thanks for contributing @olawalejuwonm 👏

**Comment by olawalejuwonm** [comment]
> Thanks for contributing @olawalejuwonm 👏

My pleasure. Would be glad to join the team to make further contributions

**Comment by Mantas97** [comment]
For open positions keep an eye on https://www.mailerlite.com/jobs

**Comment by olawalejuwonm** [comment]
Thank you

**Pull request merged**
