### PR TITLE
fix: groups on subscribers are full group objects

### LINKED ISSUE #35: subscribers.get() Does not return groups as documented
The Docs for the NodeJS SDK indicate that the call to subscribers.get() should return the list of group id's on each subscriber:

https://github.com/mailerlite/mailerlite-nodejs/blob/main/src/modules/subscribers/subscribers.module.ts

However, the groups attribute is not contained in the returned subscriber object:

image

I think this may actually be an issue with the API which also indicates that subscribers should return a list of group id's but does not either:

https://developers.mailerlite.com/docs/subscribers.html#list-all-subscribers
image

### PR DESCRIPTION
**Pull request by TobbenTM**
Resolves #35 and #36.

### CODE REVIEW

**Comment by Mantas97** [comment]
Thanks for contributing @TobbenTM. However, I have to close PR. This won't solve https://github.com/mailerlite/mailerlite-nodejs/issues/35 nor https://github.com/mailerlite/mailerlite-nodejs/issues/36. And `groups` param in `CreateOrUpdateSubscriberParams` has to be an array of ids [docs](https://developers.mailerlite.com/docs/subscribers.html#create-upsert-subscriber)

**Comment by TobbenTM** [comment]
Okay, do you have any intention to fix this yourself @Mantas97 , or do I need to maintain my own functioning fork?

**Comment by Mantas97** [comment]
@TobbenTM Mentioned issues are not isolated to SDK, they stem from API. A fix for this is planned for the near future.

**Comment by Mantas97** [comment]
@TobbenTM Fixes for #35 & #36 released in [1.2.2](https://github.com/mailerlite/mailerlite-nodejs/releases/tag/1.2.2)

**Pull request closed without merging**
